### ISSUE TITLE
Control.py not working

### ISSUE THREAD

**Issue by ankitpal1029** [NishanthARao/ROS-Quadcopter-Simulation#3]
Hello NIshanth ,
  I am planning on using your simulation for a project , 
The gazebo simulator loads but on running control.py the bot doesn't fly upwards
can you suggest what needs to be done or maybe something i missed during setup to make this run

**Comment by hakxran** [comment]
hİ, did you managed to solve your problem or do you have another drone project? I have the same problem too.

**Comment by ankitpal1029** [comment]
i made some mistake in inputting the values for the rotor speeds , thats why it wasn't working
try inputiing the rotor speeds while executing control.py
